version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - duncanmcclean
  ignore:
  - dependency-name: statamic/cms
    versions:
    - "> 3.1.0.pre.alpha.4"
  - dependency-name: statamic/cms
    versions:
    - 3.1.0-alpha.4
  - dependency-name: doublethreedigital/simple-commerce
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
    - 2.2.7
